services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - data:/data/
    #ports:
    #  - 80:80
    networks:
      - default
      - hanwg.top

volumes:
  data:

networks:
  default: # required to check password breaches
  hanwg.top:
    external: true