# https://github.com/dani-garcia/vaultwarden

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - data:/data/
    ports:
      - 90:80

volumes:
  data:
