services:
  monitoring:
    image: nicolargo/glances:latest-full
    container_name: glances
    restart: unless-stopped
    pid: host
    network_mode: host
    environment:
      - "GLANCES_OPT=-w"
    env_file:
      - .env
    ports:
      - 61209:61209