services:
  drawio:
    image: jgraph/drawio
    container_name: drawio
    restart: unless-stopped
    networks:
      - default
      - hanwg.top

networks:
  default:
    internal: true
  hanwg.top:
    external: true