services:
  homepage:
    restart: unless-stopped
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    #ports:
    #  - 2000:3000
    volumes:
      - /nas/homepage/_data:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=homepage.hanwg.top
    # added
    networks:
      - default
      - hanwg.top

# added
networks:
  default:
  hanwg.top:
    external: true