services:
  homepage:
    restart: unless-stopped
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    #ports:
    #  - 3000:3000
    volumes:
      - /nas/homepage/_data:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=homepage.hanwg.top
    networks:
      - default
      - hanwg.top

networks:
  default: # for external apis
  hanwg.top:
    external: true