services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    environment:
      UPTIME_KUMA_HIDE_LOG: 1
    volumes:
      - data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3001:3001
    restart: always

volumes:
  data: