services:
  euro-office:
    image: ghcr.io/euro-office/documentserver
    environment:
      JWT_ENABLED: true
    env_file:
      - .env
    ports:
      - "28080:80"
    volumes:
      - config:/etc/euro-office/documentserver
      - /nas/euro-office:/var/lib/euro-office/documentserver

volumes:
  config:
