services:
  vikunja:
    image: vikunja/vikunja:2.2.2
    environment:
      VIKUNJA_SERVICE_PUBLICURL: https://vijunka.hanwg.top/
      VIKUNJA_DATABASE_PATH: /db/vikunja.db
    env_file:
      - .env
    ports:
      - 3456:3456
    volumes:
      - files:/app/vikunja/files
      - db:/db
    restart: unless-stopped

volumes:
  files:
  db: