services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus
    restart: unless-stopped
    expose:
      - 9190:9090

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    expose:
      - 3100:3000
    depends_on:
      - prometheus

volumes:
  prometheus_data:
  grafana_data:
